services:
  gateway:
    image: gateway-service:1.0
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      NACOS_SERVER: 192.168.1.6
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP 消息端口
      - "15672:15672"   # 管理界面
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"       # 宿主8081 -> 容器80（8080已给gateway）
    restart: unless-stopped